export const GET_COUNTRIES="GET_COUNTRIES";
export const GET_COUNTRYID="GET_COUNTRYID";
export const GET_COUNTRY_DETAILS = "GET_COUNTRY_DETAILS";
export const GET_ACTIVITIES ="GET_ACTIVITIES";
export const FILTER_CONTINENT="FILTER_CONTINENT";
export const FILTER_POPULATION="FILTER_POPULATION";
export const FILTER_ACTIVITY="FILTER_ACTIVITY";
export const ACTION_SEARCH="ACTION_SEARCH";